In [56]:
import pandas as pd
import os

file_path = "merged_crawling_result.csv"

if os.path.exists(file_path):
    # 1. 파일 불러오기
    df = pd.read_csv(file_path, encoding="utf-8-sig")
    
    # 2. NaN 값 처리 (에러 방지용)
    df = df.fillna("")

    # ======================================================
    # [Step 1] 컬럼명(Index) 변경
    # ======================================================
    # 현재 순서: [제목, 검색어, URL, 본문, 첨부파일]
    # 변경 순서: [카테고리, 공고제목, URL, 본문, 첨부파일]
    df.columns = ["카테고리", "공고제목", "URL", "본문", "첨부파일"]
    
    # ======================================================
    # [Step 2] 본문 내 줄바꿈(\n) 제거 
    # ======================================================
    df['본문'] = df['본문'].str.replace("\n", " ", regex=False)

    print("✅ 데이터 정제 완료!")
    
    # 3. 변경된 결과 확인
    print("\n--- [수정된 데이터 미리보기] ---")
    print(df[['카테고리', '공고제목']].head()) # 잘 바뀌었는지 확인

else:
    print("⚠️ 파일이 없습니다.")

✅ 데이터 정제 완료!

--- [수정된 데이터 미리보기] ---
        카테고리                            공고제목
0  유관사업 공고조회  [대구] 2025년 4차 소상공인 맞춤형 출산ㆍ양육지원
1  유관사업 공고조회  [경기] 포천시 2026년 소공인가구지원센터 운영 지원
2  유관사업 공고조회  [부산] 2025년 폐업소상공인 희망두배통장 지원사업(
3  유관사업 공고조회  [충남] 아산시 2025년 4분기분 소상공인 사회보험료
4  유관사업 공고조회    [충남] 2026년 소상공인자금 융자 지원계획 공고

In [57]:
df

,카테고리,공고제목,URL,본문,첨부파일
0,유관사업 공고조회,[대구] 2025년 4차 소상공인 맞춤형 출산ㆍ양육지원,https://www.sbiz24.kr/#/extldPbanc/PBLN_000000...,공고명 [대구] 2025년 4차 소상공인 맞춤형 출산ㆍ양육지원 사업 모집 공고 지원...,file_download대구 소상공인 맞춤형 출산·양육지원 사업 모집 공고(25년_...
1,유관사업 공고조회,[경기] 포천시 2026년 소공인가구지원센터 운영 지원,https://www.sbiz24.kr/#/extldPbanc/PBLN_000000...,공고명 [경기] 포천시 2026년 소공인가구지원센터 운영 지원 사업 공고 지원대상 ...,file_download2026년_포천시소공인가구지원센터_운영지원사업_공고.PDF
2,유관사업 공고조회,[부산] 2025년 폐업소상공인 희망두배통장 지원사업(,https://www.sbiz24.kr/#/extldPbanc/PBLN_000000...,공고명 [부산] 2025년 폐업소상공인 희망두배통장 지원사업(2026년 이월분) 참...,"file_download폐업소상공인 희망두배통장 지원사업 공고문.HWP, file_..."
3,유관사업 공고조회,[충남] 아산시 2025년 4분기분 소상공인 사회보험료,https://www.sbiz24.kr/#/extldPbanc/PBLN_000000...,공고명 [충남] 아산시 2025년 4분기분 소상공인 사회보험료 지원사업 공고 지원대...,"file_download(공고문) 2025년 4분기 사회보험료 지원 공고.HWP, ..."
4,유관사업 공고조회,[충남] 2026년 소상공인자금 융자 지원계획 공고,https://www.sbiz24.kr/#/extldPbanc/PBLN_000000...,공고명 [충남] 2026년 소상공인자금 융자 지원계획 공고 지원대상 소상공인 소관기...,file_download2026년 충청남도 소상공인자금 융자 지원계획 공고.HWP
...,...,...,...,...,...
160,대출상품 조회,"경기도 중소기업 육성자금(소상공인 지원_점포임차자금,",https://www.sbiz24.kr/#/loanProduct/21,"기본정보 금융상품명 경기도 중소기업 육성자금(소상공인 지원_점포임차자금, 경영개선,...",
161,대출상품 조회,금융기관 협약보증,https://www.sbiz24.kr/#/loanProduct/35,기본정보 금융상품명 금융기관 협약보증 금리(%) 은행별 상이 최대한도(만원) 200...,
162,대출상품 조회,경기도 중소기업 육성자금(특별경영자금_재도전 희망특례),https://www.sbiz24.kr/#/loanProduct/28,기본정보 금융상품명 경기도 중소기업 육성자금(특별경영자금_재도전 희망특례) 금리(%...,
163,대출상품 조회,충청남도 소상공인자금,https://www.sbiz24.kr/#/loanProduct/219,기본정보 금융상품명 충청남도 소상공인자금 금리(%) 은행별 상이 최대한도(만원) 5...,
164,유관사업 공고조회,영세개인사업자의 체납액 징수특례 제도 안내,https://www.sbiz24.kr/#/extldPbanc/PBLN_000000...,공고명 영세개인사업자의 체납액 징수특례 제도 안내 지원대상 소상공인 소관기관 국세청...,file_download체납액 징수특례 제도.HWP

In [58]:
keywords = "소상공인|소공인"
mask = df['공고제목'].str.contains(keywords, na=False) | df['카테고리'].str.contains(keywords, na=False)
df_filtered = df[mask].copy() # .copy()는 경고 방지용 안전 장치

    # ======================================================
    # [추가됨] 인덱스 재설정 (0부터 순서대로)
    # ======================================================
    # drop=True: 기존의 뒤죽박죽된 인덱스를 별도 컬럼으로 남기지 않고 삭제함
df_filtered.reset_index(drop=True, inplace=True)

print(f"✅ 필터링 후 데이터 개수: {len(df_filtered)}개")
    
    # 3. 결과 확인
print("\n--- [필터링 및 인덱스 재설정 결과] ---")
print(df_filtered.head())
    
    # (확인용) 인덱스가 0, 1, 2... 로 잘 바뀌었는지 출력
    # print(df_filtered.index)

✅ 필터링 후 데이터 개수: 103개

--- [필터링 및 인덱스 재설정 결과] ---
        카테고리                            공고제목  \
0  유관사업 공고조회  [대구] 2025년 4차 소상공인 맞춤형 출산ㆍ양육지원
1  유관사업 공고조회  [경기] 포천시 2026년 소공인가구지원센터 운영 지원
2  유관사업 공고조회  [부산] 2025년 폐업소상공인 희망두배통장 지원사업(
3  유관사업 공고조회  [충남] 아산시 2025년 4분기분 소상공인 사회보험료
4  유관사업 공고조회    [충남] 2026년 소상공인자금 융자 지원계획 공고

                                                 URL  \
0  https://www.sbiz24.kr/#/extldPbanc/PBLN_000000...
1  https://www.sbiz24.kr/#/extldPbanc/PBLN_000000...
2  https://www.sbiz24.kr/#/extldPbanc/PBLN_000000...
3  https://www.sbiz24.kr/#/extldPbanc/PBLN_000000...
4  https://www.sbiz24.kr/#/extldPbanc/PBLN_000000...

                                                  본문  \
0  공고명 [대구] 2025년 4차 소상공인 맞춤형 출산ㆍ양육지원 사업 모집 공고 지원...
1  공고명 [경기] 포천시 2026년 소공인가구지원센터 운영 지원 사업 공고 지원대상 ...
2  공고명 [부산] 2025년 폐업소상공인 희망두배통장 지원사업(2026년 이월분) 참...
3  공고명 [충남] 아산시 2025년 4분기분 소상공인 사회보험료 지원사업 공고 지원대...
4  공고명 [충남] 2026년 소상공인자금 융자 지원계획 공고 지원대상 소상공인 소관기...

                                                첨부파일
0  file_download대구 소상공인 맞춤형 출산·양육지원 사업 모집 공고(25년_...
1      file_download2026년_포천시소공인가구지원센터_운영지원사업_공고.PDF
2  file_download폐업소상공인 희망두배통장 지원사업 공고문.HWP, file_...
3  file_download(공고문) 2025년 4분기 사회보험료 지원 공고.HWP, ...
4      file_download2026년 충청남도 소상공인자금 융자 지원계획 공고.HWP

In [60]:
df_filtered

,카테고리,공고제목,URL,본문,첨부파일
0,유관사업 공고조회,[대구] 2025년 4차 소상공인 맞춤형 출산ㆍ양육지원,https://www.sbiz24.kr/#/extldPbanc/PBLN_000000...,공고명 [대구] 2025년 4차 소상공인 맞춤형 출산ㆍ양육지원 사업 모집 공고 지원...,file_download대구 소상공인 맞춤형 출산·양육지원 사업 모집 공고(25년_...
1,유관사업 공고조회,[경기] 포천시 2026년 소공인가구지원센터 운영 지원,https://www.sbiz24.kr/#/extldPbanc/PBLN_000000...,공고명 [경기] 포천시 2026년 소공인가구지원센터 운영 지원 사업 공고 지원대상 ...,file_download2026년_포천시소공인가구지원센터_운영지원사업_공고.PDF
2,유관사업 공고조회,[부산] 2025년 폐업소상공인 희망두배통장 지원사업(,https://www.sbiz24.kr/#/extldPbanc/PBLN_000000...,공고명 [부산] 2025년 폐업소상공인 희망두배통장 지원사업(2026년 이월분) 참...,"file_download폐업소상공인 희망두배통장 지원사업 공고문.HWP, file_..."
3,유관사업 공고조회,[충남] 아산시 2025년 4분기분 소상공인 사회보험료,https://www.sbiz24.kr/#/extldPbanc/PBLN_000000...,공고명 [충남] 아산시 2025년 4분기분 소상공인 사회보험료 지원사업 공고 지원대...,"file_download(공고문) 2025년 4분기 사회보험료 지원 공고.HWP, ..."
4,유관사업 공고조회,[충남] 2026년 소상공인자금 융자 지원계획 공고,https://www.sbiz24.kr/#/extldPbanc/PBLN_000000...,공고명 [충남] 2026년 소상공인자금 융자 지원계획 공고 지원대상 소상공인 소관기...,file_download2026년 충청남도 소상공인자금 융자 지원계획 공고.HWP
...,...,...,...,...,...
98,대출상품 조회,BNK부산은행 특별출연 울산광역시 소기업 소상공인 금유,https://www.sbiz24.kr/#/loanProduct/123,기본정보 금융상품명 BNK부산은행 특별출연 울산광역시 소기업 소상공인 금유지원 협약...,
99,대출상품 조회,우리은행 특별출연 울산광역시 소상공인 등 금융지원 및,https://www.sbiz24.kr/#/loanProduct/122,기본정보 금융상품명 우리은행 특별출연 울산광역시 소상공인 등 금융지원 및 동반성장을...,
100,대출상품 조회,신한은행 특별출연 소기업 소상공인 따뜻한 금융지원 협약,https://www.sbiz24.kr/#/loanProduct/121,기본정보 금융상품명 신한은행 특별출연 소기업 소상공인 따뜻한 금융지원 협약보증 금리...,
101,대출상품 조회,"경기도 중소기업 육성자금(소상공인 지원_점포임차자금,",https://www.sbiz24.kr/#/loanProduct/21,"기본정보 금융상품명 경기도 중소기업 육성자금(소상공인 지원_점포임차자금, 경영개선,...",
102,대출상품 조회,충청남도 소상공인자금,https://www.sbiz24.kr/#/loanProduct/219,기본정보 금융상품명 충청남도 소상공인자금 금리(%) 은행별 상이 최대한도(만원) 5...,

In [61]:
df_filtered = df_filtered.drop(["URL"], axis=1)

In [62]:
df_filtered

,카테고리,공고제목,본문,첨부파일
0,유관사업 공고조회,[대구] 2025년 4차 소상공인 맞춤형 출산ㆍ양육지원,공고명 [대구] 2025년 4차 소상공인 맞춤형 출산ㆍ양육지원 사업 모집 공고 지원...,file_download대구 소상공인 맞춤형 출산·양육지원 사업 모집 공고(25년_...
1,유관사업 공고조회,[경기] 포천시 2026년 소공인가구지원센터 운영 지원,공고명 [경기] 포천시 2026년 소공인가구지원센터 운영 지원 사업 공고 지원대상 ...,file_download2026년_포천시소공인가구지원센터_운영지원사업_공고.PDF
2,유관사업 공고조회,[부산] 2025년 폐업소상공인 희망두배통장 지원사업(,공고명 [부산] 2025년 폐업소상공인 희망두배통장 지원사업(2026년 이월분) 참...,"file_download폐업소상공인 희망두배통장 지원사업 공고문.HWP, file_..."
3,유관사업 공고조회,[충남] 아산시 2025년 4분기분 소상공인 사회보험료,공고명 [충남] 아산시 2025년 4분기분 소상공인 사회보험료 지원사업 공고 지원대...,"file_download(공고문) 2025년 4분기 사회보험료 지원 공고.HWP, ..."
4,유관사업 공고조회,[충남] 2026년 소상공인자금 융자 지원계획 공고,공고명 [충남] 2026년 소상공인자금 융자 지원계획 공고 지원대상 소상공인 소관기...,file_download2026년 충청남도 소상공인자금 융자 지원계획 공고.HWP
...,...,...,...,...
98,대출상품 조회,BNK부산은행 특별출연 울산광역시 소기업 소상공인 금유,기본정보 금융상품명 BNK부산은행 특별출연 울산광역시 소기업 소상공인 금유지원 협약...,
99,대출상품 조회,우리은행 특별출연 울산광역시 소상공인 등 금융지원 및,기본정보 금융상품명 우리은행 특별출연 울산광역시 소상공인 등 금융지원 및 동반성장을...,
100,대출상품 조회,신한은행 특별출연 소기업 소상공인 따뜻한 금융지원 협약,기본정보 금융상품명 신한은행 특별출연 소기업 소상공인 따뜻한 금융지원 협약보증 금리...,
101,대출상품 조회,"경기도 중소기업 육성자금(소상공인 지원_점포임차자금,","기본정보 금융상품명 경기도 중소기업 육성자금(소상공인 지원_점포임차자금, 경영개선,...",
102,대출상품 조회,충청남도 소상공인자금,기본정보 금융상품명 충청남도 소상공인자금 금리(%) 은행별 상이 최대한도(만원) 5...,

In [63]:
save_filename = "so_sang_gong_in_data.csv" # 원하는 파일명
df_filtered.to_csv(save_filename, index=False, encoding="utf-8-sig")