In [66]:
df

,카테고리,공고제목,본문,첨부파일
0,유관사업 공고조회,[대구] 2025년 4차 소상공인 맞춤형 출산ㆍ양육지원,공고명 [대구] 2025년 4차 소상공인 맞춤형 출산ㆍ양육지원 사업 모집 공고 지원...,file_download대구 소상공인 맞춤형 출산·양육지원 사업 모집 공고(25년_...
1,유관사업 공고조회,[경기] 포천시 2026년 소공인가구지원센터 운영 지원,공고명 [경기] 포천시 2026년 소공인가구지원센터 운영 지원 사업 공고 지원대상 ...,file_download2026년_포천시소공인가구지원센터_운영지원사업_공고.PDF
2,유관사업 공고조회,[부산] 2025년 폐업소상공인 희망두배통장 지원사업(,공고명 [부산] 2025년 폐업소상공인 희망두배통장 지원사업(2026년 이월분) 참...,"file_download폐업소상공인 희망두배통장 지원사업 공고문.HWP, file_..."
3,유관사업 공고조회,[충남] 아산시 2025년 4분기분 소상공인 사회보험료,공고명 [충남] 아산시 2025년 4분기분 소상공인 사회보험료 지원사업 공고 지원대...,"file_download(공고문) 2025년 4분기 사회보험료 지원 공고.HWP, ..."
4,유관사업 공고조회,[충남] 2026년 소상공인자금 융자 지원계획 공고,공고명 [충남] 2026년 소상공인자금 융자 지원계획 공고 지원대상 소상공인 소관기...,file_download2026년 충청남도 소상공인자금 융자 지원계획 공고.HWP
...,...,...,...,...
98,대출상품 조회,BNK부산은행 특별출연 울산광역시 소기업 소상공인 금유,기본정보 금융상품명 BNK부산은행 특별출연 울산광역시 소기업 소상공인 금유지원 협약...,
99,대출상품 조회,우리은행 특별출연 울산광역시 소상공인 등 금융지원 및,기본정보 금융상품명 우리은행 특별출연 울산광역시 소상공인 등 금융지원 및 동반성장을...,
100,대출상품 조회,신한은행 특별출연 소기업 소상공인 따뜻한 금융지원 협약,기본정보 금융상품명 신한은행 특별출연 소기업 소상공인 따뜻한 금융지원 협약보증 금리...,
101,대출상품 조회,"경기도 중소기업 육성자금(소상공인 지원_점포임차자금,","기본정보 금융상품명 경기도 중소기업 육성자금(소상공인 지원_점포임차자금, 경영개선,...",
102,대출상품 조회,충청남도 소상공인자금,기본정보 금융상품명 충청남도 소상공인자금 금리(%) 은행별 상이 최대한도(만원) 5...,

In [67]:
df = df.drop("첨부파일", axis=1)

In [68]:
df

,카테고리,공고제목,본문
0,유관사업 공고조회,[대구] 2025년 4차 소상공인 맞춤형 출산ㆍ양육지원,공고명 [대구] 2025년 4차 소상공인 맞춤형 출산ㆍ양육지원 사업 모집 공고 지원...
1,유관사업 공고조회,[경기] 포천시 2026년 소공인가구지원센터 운영 지원,공고명 [경기] 포천시 2026년 소공인가구지원센터 운영 지원 사업 공고 지원대상 ...
2,유관사업 공고조회,[부산] 2025년 폐업소상공인 희망두배통장 지원사업(,공고명 [부산] 2025년 폐업소상공인 희망두배통장 지원사업(2026년 이월분) 참...
3,유관사업 공고조회,[충남] 아산시 2025년 4분기분 소상공인 사회보험료,공고명 [충남] 아산시 2025년 4분기분 소상공인 사회보험료 지원사업 공고 지원대...
4,유관사업 공고조회,[충남] 2026년 소상공인자금 융자 지원계획 공고,공고명 [충남] 2026년 소상공인자금 융자 지원계획 공고 지원대상 소상공인 소관기...
...,...,...,...
98,대출상품 조회,BNK부산은행 특별출연 울산광역시 소기업 소상공인 금유,기본정보 금융상품명 BNK부산은행 특별출연 울산광역시 소기업 소상공인 금유지원 협약...
99,대출상품 조회,우리은행 특별출연 울산광역시 소상공인 등 금융지원 및,기본정보 금융상품명 우리은행 특별출연 울산광역시 소상공인 등 금융지원 및 동반성장을...
100,대출상품 조회,신한은행 특별출연 소기업 소상공인 따뜻한 금융지원 협약,기본정보 금융상품명 신한은행 특별출연 소기업 소상공인 따뜻한 금융지원 협약보증 금리...
101,대출상품 조회,"경기도 중소기업 육성자금(소상공인 지원_점포임차자금,","기본정보 금융상품명 경기도 중소기업 육성자금(소상공인 지원_점포임차자금, 경영개선,..."
102,대출상품 조회,충청남도 소상공인자금,기본정보 금융상품명 충청남도 소상공인자금 금리(%) 은행별 상이 최대한도(만원) 5...

In [69]:
category_list = df['카테고리'].unique().tolist()

print("✅ 카테고리 종류:")
print(category_list)

✅ 카테고리 종류:
['유관사업 공고조회', '소진공 공고조회', '대출상품 조회']

In [70]:
# 1. 데이터를 담을 딕셔너리 생성
dfs = {}

# 2. 각 카테고리명 리스트
categories = ['유관사업 공고조회', '소진공 공고조회', '대출상품 조회']

# 3. 반복문을 통해 필터링 및 할당
for cat in categories:
    # 해당 카테고리에 맞는 행만 추출하여 복사본 저장
    dfs[cat] = df_filtered[df_filtered['카테고리'] == cat].copy()
    
    # 인덱스 재설정 (0부터 다시 시작하도록)
    dfs[cat].reset_index(drop=True, inplace=True)
    
    print(f"✅ '{cat}' 데이터프레임 생성 완료: {len(dfs[cat])}건")

# ==========================================
# 4. 개별 변수로 사용하고 싶을 경우
# ==========================================
df_yugwan = dfs['유관사업 공고조회']
df_sojingong = dfs['소진공 공고조회']
df_loan = dfs['대출상품 조회']

✅ '유관사업 공고조회' 데이터프레임 생성 완료: 12건
✅ '소진공 공고조회' 데이터프레임 생성 완료: 43건
✅ '대출상품 조회' 데이터프레임 생성 완료: 48건

In [71]:
import pandas as pd
import re

def parse_yugwan_text(text):
    """
    본문 텍스트를 분석하여 항목별로 내용을 추출하는 함수
    """
    # 1. 불필요한 뒷부분 제거 ('카카오톡으로 공유하기' 이후 삭제)
    if "카카오톡으로 공유하기" in text:
        text = text.split("카카오톡으로 공유하기")[0]
    
    # 2. 추출할 키워드 리스트 (순서 중요!)
    # 정규표현식에서 괄호()는 특수문자이므로 앞에 역슬래시(\)를 붙여야 합니다.
    keywords = [
        "공고명", "지원대상", "소관기관", "지원분야\(대\)", "지원분야\(중\)",
        "사업수행기관", "문의처", "신청기간", "공고내용", 
        "사업신청방법설명", "첨부파일"
    ]
    
    parsed_data = {}
    
    for i in range(len(keywords)):
        current_keyword = keywords[i]
        
        # 다음 키워드가 있는지 확인 (마지막 키워드인 '첨부파일' 제외)
        next_keyword = keywords[i+1] if i < len(keywords) - 1 else None
        
        # 딕셔너리에 저장할 깔끔한 키 이름 (괄호 이스케이프 제거)
        clean_key = current_keyword.replace(r"\(", "(").replace(r"\)", ")")
        
        try:
            # 현재 키워드의 위치 찾기
            start_match = re.search(current_keyword, text)
            if not start_match:
                parsed_data[clean_key] = "" # 키워드가 없으면 빈칸
                continue
                
            start_index = start_match.end() # 키워드 끝나는 지점부터 내용 시작
            
            # 다음 키워드 위치 찾기 (내용의 끝 지점)
            end_index = len(text) # 기본값: 텍스트 끝까지
            if next_keyword:
                next_match = re.search(next_keyword, text)
                if next_match:
                    end_index = next_match.start() # 다음 키워드 시작 지점 전까지
            
            # 내용 추출 및 공백 제거
            content = text[start_index:end_index].strip()
            parsed_data[clean_key] = content
            
        except Exception as e:
            parsed_data[clean_key] = ""

    return pd.Series(parsed_data)

# ==========================================
# 실행 코드
# ==========================================

# 1. 빈 데이터프레임 방지 (데이터가 있을 때만 실행)
if not df_yugwan.empty:
    print("⏳ 본문 내용 분리 작업을 시작합니다...")

    # 2. 본문 컬럼에 함수 적용하여 새로운 컬럼들 생성
    # apply를 쓰면 각 행마다 함수가 실행되고, 결과가 새로운 데이터프레임으로 반환됩니다.
    extracted_cols = df_yugwan['본문'].apply(parse_yugwan_text)
    
    # 3. 기존 df_yugwan과 합치기 (기존 '본문' 컬럼은 제거하거나 유지 선택 가능)
    # 여기서는 보기 좋게 '본문'을 빼고 합칩니다.
    df_yugwan_final = pd.concat([df_yugwan.drop('본문', axis=1), extracted_cols], axis=1)
    
    print("✅ 분리 완료!")
    
    # 4. 결과 확인
    print("\n--- [분리된 데이터 미리보기] ---")
    # 화면에 잘 보이게 공고명과 지원대상만 먼저 출력
    print(df_yugwan_final[['공고제목', '지원대상', '소관기관', '첨부파일']].head(3))
    
    # 전체 컬럼명 확인
    print("\n--- [생성된 컬럼 목록] ---")
    print(df_yugwan_final.columns.tolist())

else:
    print("⚠️ df_yugwan 데이터가 비어있습니다.")

⏳ 본문 내용 분리 작업을 시작합니다...
✅ 분리 완료!

--- [분리된 데이터 미리보기] ---
                             공고제목  지원대상   소관기관  \
0  [대구] 2025년 4차 소상공인 맞춤형 출산ㆍ양육지원  소상공인  대구광역시
1  [경기] 포천시 2026년 소공인가구지원센터 운영 지원  소상공인    경기도
2  [부산] 2025년 폐업소상공인 희망두배통장 지원사업(  소상공인  부산광역시

                                                첨부파일  \
0  file_download대구 소상공인 맞춤형 출산·양육지원 사업 모집 공고(25년_...
1      file_download2026년_포천시소공인가구지원센터_운영지원사업_공고.PDF
2  file_download폐업소상공인 희망두배통장 지원사업 공고문.HWP, file_...

                                                첨부파일
0  file_download대구 소상공인 맞춤형 출산·양육지원 사업 모집 공고(25년_...
1      file_download2026년_포천시소공인가구지원센터_운영지원사업_공고.PDF
2  file_download폐업소상공인 희망두배통장 지원사업 공고문.HWP file_d...

--- [생성된 컬럼 목록] ---
['카테고리', '공고제목', '첨부파일', '공고명', '지원대상', '소관기관', '지원분야(대)', '지원분야(중)', '사업수행기관', '문의처', '신청기간', '공고내용', '사업신청방법설명', '첨부파일']

In [73]:
df_yugwan_final

,카테고리,공고제목,첨부파일,공고명,지원대상,소관기관,지원분야(대),지원분야(중),사업수행기관,문의처,신청기간,공고내용,사업신청방법설명,첨부파일
0,유관사업 공고조회,[대구] 2025년 4차 소상공인 맞춤형 출산ㆍ양육지원,file_download대구 소상공인 맞춤형 출산·양육지원 사업 모집 공고(25년_...,[대구] 2025년 4차 소상공인 맞춤형 출산ㆍ양육지원 사업 모집 공고,소상공인,대구광역시,인력,고용유지,대구광역시행복진흥사회서비스원,대구광역시행복진흥사회서비스원 여성가족사업팀 출산 소상공인 양육비 지원 053-210...,예산 소진시까지,경기 침체 등으로 어려움을 겪고 있는 대구지역 소상공인의 출산·양육 지원을 통해 저...,이메일 접수 - 출산 소상공인 양육비 지원 : syj8017@daegu.pass.o...,file_download대구 소상공인 맞춤형 출산·양육지원 사업 모집 공고(25년_...
1,유관사업 공고조회,[경기] 포천시 2026년 소공인가구지원센터 운영 지원,file_download2026년_포천시소공인가구지원센터_운영지원사업_공고.PDF,[경기] 포천시 2026년 소공인가구지원센터 운영 지원 사업 공고,소상공인,경기도,경영,디자인/상품화/사업화,경기대진테크노파크,경기대진테크노파크 소공인지원팀 (031-539-5153),2026-01-06 ~ 2026-12-31,(재)경기대진테크노파크는 포천시 소재 가구ㆍ공예 제조 소공인의 안정적인 재기와 성장...,"방문 및 이메일, 팩스 접수 - 접수처 : (11165) 경기도 포천시 가산면 포천...",file_download2026년_포천시소공인가구지원센터_운영지원사업_공고.PDF
2,유관사업 공고조회,[부산] 2025년 폐업소상공인 희망두배통장 지원사업(,"file_download폐업소상공인 희망두배통장 지원사업 공고문.HWP, file_...",[부산] 2025년 폐업소상공인 희망두배통장 지원사업(2026년 이월분) 참여자 추...,소상공인,부산광역시,경영,시설/입지지원,부산경제진흥원,"부산경제진흥원 산업인력지원단 051-888-6902, 6904",예산 소진시까지,부산경제진흥원에서는 2025년 1월 1일 이후 취업한 폐업소상공인에게 「희망두배통장...,온라인 접수 (부산일자리정보망),file_download폐업소상공인 희망두배통장 지원사업 공고문.HWP file_d...
3,유관사업 공고조회,[충남] 아산시 2025년 4분기분 소상공인 사회보험료,"file_download(공고문) 2025년 4분기 사회보험료 지원 공고.HWP, ...",[충남] 아산시 2025년 4분기분 소상공인 사회보험료 지원사업 공고,소상공인,충청남도,금융,보험(수출+무역),기초자치단체,아산시청 지역경제과 041-530-6041,2026-01-05 ~ 2026-01-23,아산시 영세 소상공인의 경영 부담을 완화하고 근로자의 고용불안 해소를 위하여「소상공...,방문 또는 이메일 접수 - 접수처 : 아산시청 별관 3층 지역경제과 - 이메일 : ...,file_download(공고문) 2025년 4분기 사회보험료 지원 공고.HWP f...
4,유관사업 공고조회,[충남] 2026년 소상공인자금 융자 지원계획 공고,file_download2026년 충청남도 소상공인자금 융자 지원계획 공고.HWP,[충남] 2026년 소상공인자금 융자 지원계획 공고,소상공인,충청남도,금융,융자,충남신용보증재단,충남 신용보증재단 본점 1588-7310 영업점별 문의처 공고문 9p 참조,예산 소진시까지,「충청남도 중소기업육성기금 설치 및 운용 조례」 제20조 및 같은 조례 시행규칙 제...,온라인 및 방문 접수 - 온라인 : 신용보증재단 보증드림 앱(App) 또는 각 은행...,file_download2026년 충청남도 소상공인자금 융자 지원계획 공고.HWP
5,유관사업 공고조회,[대전] 유성구 2026년 소상공인 특례보증 지원사업,file_download2026년 유성구 소상공인 특례보증 지원사업 공고.HWP,[대전] 유성구 2026년 소상공인 특례보증 지원사업 공고,소상공인,대전광역시,금융,융자,기초자치단체,"유성구 일자리정책과(042-611-2099), 대전신용보증재단 유성지점(042-38...",예산 소진시까지,장기화된 경기침체 및 소비심리 위축 등으로 피해가 극심한 소상공인의 경영애로를 해소...,온라인 접수(보증드림 앱 또는 하나은행 앱) ※ 만 70세이상 고령자 대면 접수 가...,file_download2026년 유성구 소상공인 특례보증 지원사업 공고.HWP
6,유관사업 공고조회,[부산] 사상구 2026년 소상공인 보증료 지원사업 대,file_download공고문(2026년 소상공인 보증료 지원사업).HWP,[부산] 사상구 2026년 소상공인 보증료 지원사업 대상자 모집 공고,소상공인,부산광역시,금융,보증,기초자치단체,사상구청 일자리경제과 051-310-4616,예산 소진시까지,"「부산광역시 사상구 소상공인 지원에 관한 조례」 제6조(창업 및 경영 안정 지원),...",온라인 및 방문 접수 - 온라인 : 구 홈페이지 - 접수처 : 부상광역시 사상구청 ...,file_download공고문(2026년 소상공인 보증료 지원사업).HWP
7,유관사업 공고조회,[경북] 소상공인 비즈니스플랜 콘테스트 보조사업자 모집,file_download소상공인 비즈니스 플랜 콘테스트 공모 공고.HWP,[경북] 소상공인 비즈니스플랜 콘테스트 보조사업자 모집 공고,사회적기업,경상북도,경영,컨설팅,직접수행,경상북도 민생경제과 소상공인팀 (054-880-2632),2025-12-30 ~ 2026-01-14,"지방자치단체 보조금 관리에 관한 법률 제7조, 경상북도 보조금 관리 조례 제5조의 ...",온라인 접수 (지방보조금관리시스템(보탬e)),file_download소상공인 비즈니스 플랜 콘테스트 공모 공고.HWP
8,유관사업 공고조회,[경북] 2026년 소상공인육성자금(경북버팀금융) 이차,file_download2026년도 소상공인육성자금 지원 계획.HWP,[경북] 2026년 소상공인육성자금(경북버팀금융) 이차보전 지원 계획 공고,소상공인,경상북도,금융,융자,경북신용보증재단,기업지원과 054-880-2679 및 영업점별 문의처 공고문 p.5 참조,상시 접수,담보력이 부족한 지역 소상공인에게 신용보증을 통한 융자지원 및 대출이자 지원으로 서...,방문 및 온라인 접수 - 접수처 : 경북신용보증재단 사업장 소재지 관할 영업점 및 ...,file_download2026년도 소상공인육성자금 지원 계획.HWP
9,유관사업 공고조회,[강원] 정선군 2026년 소상공인 시설개선사업 시행,file_download2026년도 정선군 소상공인 시설개선사업 공고문.HWP,[강원] 정선군 2026년 소상공인 시설개선사업 시행 공고,소상공인,강원특별자치도,경영,시설/입지지원,정선군상권활성화재단,정선군상권활성화재단 033-563-9973 및 읍ㆍ면 행정복지센터 산업개발팀 문의처...,2026-01-02 ~ 2026-01-23,「소상공인 기본법」 제3조(정부와 지방자치단체의 책무) 및「정선군 소상공인 지원에 ...,방문 접수 - 접수처 : 읍ㆍ면 행정복지센터 산업개발팀,file_download2026년도 정선군 소상공인 시설개선사업 공고문.HWP
10,유관사업 공고조회,[경북] 2025년 3차 출산육아 소상공인 전기료 지원,"file_download1. (본문)공고문.PDF, file_download2. (...",[경북] 2025년 3차 출산육아 소상공인 전기료 지원 모집 공고,중소기업,경상북도,인력,고용유지,경상북도경제진흥원,"경상북도경제진흥원 소상공인지원팀 1800-8730, khw0191@gepa.kr",2025-12-15 ~ 2026-01-09,"경상북도와 KB금융, (재)경상북도경제진흥원에서는 도내 출산 육아 소상공인의 전기료...",온라인 접수 ※ 신청서 다운로드 및 작성 및 서명하여 경상북도 ‘모이소 앱’으로 접...,file_download1. (본문)공고문.PDF file_download2. (서...
11,유관사업 공고조회,[충북] 2025년 소상공인 출산지원 시범사업 참여자,file_download2025년 소상공인 출산지원 시범사업 참여자 모집공고.PNG,[충북] 2025년 소상공인 출산지원 시범사업 참여자 모집 공고,소상공인,충청북도,인력,고용환경개선,충청북도기업진흥원,신청시스템(소상공인24) 1644-5302 및 시군지역별 문의처 공고문 P.5 참조,예산 소진시까지,충북도내 소상공인의 출산 및 육아로 인해 경영에서 일시적으로 이탈하는 경우 대체인력...,온라인 접수 (소상공인24),file_download2025년 소상공인 출산지원 시범사업 참여자 모집공고.PNG

In [76]:
df_yugwan_final = df_yugwan_final.drop(["공고제목","첨부파일"], axis=1)

In [77]:
df_yugwan_final

,카테고리,공고명,지원대상,소관기관,지원분야(대),지원분야(중),사업수행기관,문의처,신청기간,공고내용,사업신청방법설명
0,유관사업 공고조회,[대구] 2025년 4차 소상공인 맞춤형 출산ㆍ양육지원 사업 모집 공고,소상공인,대구광역시,인력,고용유지,대구광역시행복진흥사회서비스원,대구광역시행복진흥사회서비스원 여성가족사업팀 출산 소상공인 양육비 지원 053-210...,예산 소진시까지,경기 침체 등으로 어려움을 겪고 있는 대구지역 소상공인의 출산·양육 지원을 통해 저...,이메일 접수 - 출산 소상공인 양육비 지원 : syj8017@daegu.pass.o...
1,유관사업 공고조회,[경기] 포천시 2026년 소공인가구지원센터 운영 지원 사업 공고,소상공인,경기도,경영,디자인/상품화/사업화,경기대진테크노파크,경기대진테크노파크 소공인지원팀 (031-539-5153),2026-01-06 ~ 2026-12-31,(재)경기대진테크노파크는 포천시 소재 가구ㆍ공예 제조 소공인의 안정적인 재기와 성장...,"방문 및 이메일, 팩스 접수 - 접수처 : (11165) 경기도 포천시 가산면 포천..."
2,유관사업 공고조회,[부산] 2025년 폐업소상공인 희망두배통장 지원사업(2026년 이월분) 참여자 추...,소상공인,부산광역시,경영,시설/입지지원,부산경제진흥원,"부산경제진흥원 산업인력지원단 051-888-6902, 6904",예산 소진시까지,부산경제진흥원에서는 2025년 1월 1일 이후 취업한 폐업소상공인에게 「희망두배통장...,온라인 접수 (부산일자리정보망)
3,유관사업 공고조회,[충남] 아산시 2025년 4분기분 소상공인 사회보험료 지원사업 공고,소상공인,충청남도,금융,보험(수출+무역),기초자치단체,아산시청 지역경제과 041-530-6041,2026-01-05 ~ 2026-01-23,아산시 영세 소상공인의 경영 부담을 완화하고 근로자의 고용불안 해소를 위하여「소상공...,방문 또는 이메일 접수 - 접수처 : 아산시청 별관 3층 지역경제과 - 이메일 : ...
4,유관사업 공고조회,[충남] 2026년 소상공인자금 융자 지원계획 공고,소상공인,충청남도,금융,융자,충남신용보증재단,충남 신용보증재단 본점 1588-7310 영업점별 문의처 공고문 9p 참조,예산 소진시까지,「충청남도 중소기업육성기금 설치 및 운용 조례」 제20조 및 같은 조례 시행규칙 제...,온라인 및 방문 접수 - 온라인 : 신용보증재단 보증드림 앱(App) 또는 각 은행...
5,유관사업 공고조회,[대전] 유성구 2026년 소상공인 특례보증 지원사업 공고,소상공인,대전광역시,금융,융자,기초자치단체,"유성구 일자리정책과(042-611-2099), 대전신용보증재단 유성지점(042-38...",예산 소진시까지,장기화된 경기침체 및 소비심리 위축 등으로 피해가 극심한 소상공인의 경영애로를 해소...,온라인 접수(보증드림 앱 또는 하나은행 앱) ※ 만 70세이상 고령자 대면 접수 가...
6,유관사업 공고조회,[부산] 사상구 2026년 소상공인 보증료 지원사업 대상자 모집 공고,소상공인,부산광역시,금융,보증,기초자치단체,사상구청 일자리경제과 051-310-4616,예산 소진시까지,"「부산광역시 사상구 소상공인 지원에 관한 조례」 제6조(창업 및 경영 안정 지원),...",온라인 및 방문 접수 - 온라인 : 구 홈페이지 - 접수처 : 부상광역시 사상구청 ...
7,유관사업 공고조회,[경북] 소상공인 비즈니스플랜 콘테스트 보조사업자 모집 공고,사회적기업,경상북도,경영,컨설팅,직접수행,경상북도 민생경제과 소상공인팀 (054-880-2632),2025-12-30 ~ 2026-01-14,"지방자치단체 보조금 관리에 관한 법률 제7조, 경상북도 보조금 관리 조례 제5조의 ...",온라인 접수 (지방보조금관리시스템(보탬e))
8,유관사업 공고조회,[경북] 2026년 소상공인육성자금(경북버팀금융) 이차보전 지원 계획 공고,소상공인,경상북도,금융,융자,경북신용보증재단,기업지원과 054-880-2679 및 영업점별 문의처 공고문 p.5 참조,상시 접수,담보력이 부족한 지역 소상공인에게 신용보증을 통한 융자지원 및 대출이자 지원으로 서...,방문 및 온라인 접수 - 접수처 : 경북신용보증재단 사업장 소재지 관할 영업점 및 ...
9,유관사업 공고조회,[강원] 정선군 2026년 소상공인 시설개선사업 시행 공고,소상공인,강원특별자치도,경영,시설/입지지원,정선군상권활성화재단,정선군상권활성화재단 033-563-9973 및 읍ㆍ면 행정복지센터 산업개발팀 문의처...,2026-01-02 ~ 2026-01-23,「소상공인 기본법」 제3조(정부와 지방자치단체의 책무) 및「정선군 소상공인 지원에 ...,방문 접수 - 접수처 : 읍ㆍ면 행정복지센터 산업개발팀
10,유관사업 공고조회,[경북] 2025년 3차 출산육아 소상공인 전기료 지원 모집 공고,중소기업,경상북도,인력,고용유지,경상북도경제진흥원,"경상북도경제진흥원 소상공인지원팀 1800-8730, khw0191@gepa.kr",2025-12-15 ~ 2026-01-09,"경상북도와 KB금융, (재)경상북도경제진흥원에서는 도내 출산 육아 소상공인의 전기료...",온라인 접수 ※ 신청서 다운로드 및 작성 및 서명하여 경상북도 ‘모이소 앱’으로 접...
11,유관사업 공고조회,[충북] 2025년 소상공인 출산지원 시범사업 참여자 모집 공고,소상공인,충청북도,인력,고용환경개선,충청북도기업진흥원,신청시스템(소상공인24) 1644-5302 및 시군지역별 문의처 공고문 P.5 참조,예산 소진시까지,충북도내 소상공인의 출산 및 육아로 인해 경영에서 일시적으로 이탈하는 경우 대체인력...,온라인 접수 (소상공인24)

In [82]:
import pandas as pd
import re

def parse_sojingong_text(text):
    """
    소진공 공고조회 본문 텍스트를 분석하여 항목별로 추출하는 함수
    """
    # 1. 불필요한 뒷부분 제거 ('카카오톡으로 공유하기' 이후 삭제)
    if "카카오톡으로 공유하기" in text:
        text = text.split("카카오톡으로 공유하기")[0]
    
    # 2. 텍스트 내 실제 등장하는 키워드 순서 (그대로 적어야 함)
    # 주의: 텍스트에는 '모집유형'으로 적혀있지만, 나중에 '공고대상'으로 저장할 것입니다.
    # 주의: '공고문 미리보기'는 띄어쓰기가 포함되어 있습니다.
    raw_keywords = [
        "공고명", "모집유형", "지원사업유형명", "사업기간", "접수기간",
        "공고내용", "공고문 미리보기", "첨부파일", "연관주제어", "상담신청기간"
    ]
    
    # 3. (옵션) 텍스트의 키워드 -> 내가 원하는 컬럼명으로 변경 매핑
    col_mapping = {
        "모집유형": "공고대상",          # 요청하신 이름으로 변경
        "공고문 미리보기": "공고문미리보기" # 띄어쓰기 제거
    }
    
    parsed_data = {}
    
    for i in range(len(raw_keywords)):
        current_keyword = raw_keywords[i]
        
        # 다음 키워드가 있는지 확인
        next_keyword = raw_keywords[i+1] if i < len(raw_keywords) - 1 else None
        
        # 저장할 컬럼명 결정 (매핑에 있으면 그거 쓰고, 없으면 원래 이름 사용)
        save_col_name = col_mapping.get(current_keyword, current_keyword)
        
        try:
            # 현재 키워드 위치 찾기
            start_match = re.search(current_keyword, text)
            if not start_match:
                parsed_data[save_col_name] = ""
                continue
                
            start_index = start_match.end() # 키워드 끝나는 지점
            
            # 다음 키워드 위치 찾기
            end_index = len(text)
            if next_keyword:
                next_match = re.search(next_keyword, text)
                if next_match:
                    end_index = next_match.start()
            
            # 내용 추출 및 공백 제거
            content = text[start_index:end_index].strip()
            parsed_data[save_col_name] = content
            
        except Exception as e:
            parsed_data[save_col_name] = ""

    return pd.Series(parsed_data)

# ==========================================
# 실행 코드
# ==========================================

if not df_sojingong.empty:
    print("⏳ 소진공 데이터 분리 작업을 시작합니다...")

    # 1. 함수 적용
    extracted_cols = df_sojingong['본문'].apply(parse_sojingong_text)
    
    # 2. 기존 df_sojingong과 합치기 (기존 '본문' 제거)
    df_sojingong_final = pd.concat([df_sojingong.drop('본문', axis=1), extracted_cols], axis=1)
    
    print("✅ 소진공 데이터 정제 완료!")
    
    # 3. 결과 확인
    # 요청하신 주요 컬럼 미리보기
    target_cols_preview = ['공고명', '공고대상', '접수기간', '첨부파일']
    print("\n--- [분리된 데이터 미리보기] ---")
    print(df_sojingong_final[target_cols_preview].head(3))
    
    # 전체 컬럼명 확인
    print("\n--- [생성된 컬럼 목록] ---")
    print(df_sojingong_final.columns.tolist())

else:
    print("⚠️ df_sojingong 데이터가 비어있습니다.")

⏳ 소진공 데이터 분리 작업을 시작합니다...
✅ 소진공 데이터 정제 완료!

--- [분리된 데이터 미리보기] ---
                              공고명        공고대상  \
0   2026년 중소벤처기업부 소상공인 지원사업 통합 공고        소상공인
1        2026년 소상공인 고용보험료 지원사업 공고        소상공인
2  서울 문래 기계금속 소공인특화지원센터 소공인 모집 공고  소상공인/예비창업자

                                  접수기간  \
0  2025-12-01 00:00 ~ 2026-12-31 00:00
1  2026-01-01 00:00 ~ 2026-12-31 23:59
2  2025-07-01 00:00 ~ 2026-02-01 00:00

                                                첨부파일  \
0  file_download2026년_중소벤처기업부_소상공인_지원사업_통합_공고.PDF...
1  file_download「2026년_소상공인_고용보험료_지원사업」공고.HWP [1....
2

                                                첨부파일
0  file_download2026년_중소벤처기업부_소상공인_지원사업_통합_공고.PDF...
1  을 확인하여 주시기 바랍니다. 공고문 미리보기 첨부파일 file_download 전...
2

--- [생성된 컬럼 목록] ---
['카테고리', '공고제목', '첨부파일', '공고명', '공고대상', '지원사업유형명', '사업기간', '접수기간', '공고내용', '공고문미리보기', '첨부파일', '연관주제어', '상담신청기간']

In [84]:
df_sojingong_final = df_sojingong_final.drop(["첨부파일","공고명","공고문미리보기","상담신청기간","연관주제어"], axis=1)

In [85]:
df_sojingong_final

,카테고리,공고제목,공고대상,지원사업유형명,사업기간,접수기간,공고내용
0,소진공 공고조회,2026년 중소벤처기업부 소상공인 지원사업 통합 공고,소상공인,소상공인24-소상공인24 미사용 사업 공고등록 전용,2026-01-01 ~ 2026-12-31,2025-12-01 00:00 ~ 2026-12-31 00:00,중소벤처기업부 공고 제2025-652호 2026년 중소벤처기업부 소상공인 지원사...
1,소진공 공고조회,2026년 소상공인 고용보험료 지원사업 공고,소상공인,자영업자 고용보험료 지원사업-자영업자 고용보험료 지원사업,2026-01-01 ~ 2026-12-31,2026-01-01 00:00 ~ 2026-12-31 23:59,「2026년 소상공인 고용보험료 지원사업」 공고 소상공인에게 보험료를 지원하여 ‘...
2,소진공 공고조회,서울 문래 기계금속 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-07-01 ~ 2026-01-31,2025-07-01 00:00 ~ 2026-02-01 00:00,서울 문래 기계금속 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 ...
3,소진공 공고조회,서울 상생 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-07-01 ~ 2026-01-31,2025-07-01 00:00 ~ 2026-02-01 00:00,서울 상생 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소공인의 ...
4,소진공 공고조회,파주 출판인쇄 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-07-01 ~ 2026-01-31,2025-07-01 00:00 ~ 2026-01-31 00:00,파주 출판인쇄 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소공인...
5,소진공 공고조회,무안 도자 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-02-01 ~ 2026-01-31,2025-04-22 00:00 ~ 2026-01-31 00:00,무안 도자 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소공인의 ...
6,소진공 공고조회,포천 가산 가구 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-03-31 ~ 2026-01-31,2025-04-16 00:00 ~ 2026-01-31 23:59,포천 가산 가구 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소공...
7,소진공 공고조회,전북 상생 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-16 ~ 2026-01-31,2025-04-16 00:00 ~ 2026-01-31 23:59,전북 상생 소공인특화지원센터 지원사업 모집 공고 소공인의 집적지 활성화와 소공인의...
8,소진공 공고조회,경남 상생 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-16 ~ 2026-01-31,2025-04-16 00:00 ~ 2026-01-31 23:59,경남 상생 소공인특화지원센터 지원사업 모집 공고 소공인의 집적지 활성화와 소공인의...
9,소진공 공고조회,서울 창신 의류제조 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-02-01 ~ 2026-01-31,2025-04-11 00:00 ~ 2026-01-31 00:00,서울 창신 의류제조 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 ...
10,소진공 공고조회,영월 식품제조 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-02-01 ~ 2026-01-31,2025-04-09 00:00 ~ 2026-01-31 00:00,영월 식품제조 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소공인...
11,소진공 공고조회,전주 팔복 금속가공 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-02-01 ~ 2026-01-31,2025-04-09 00:00 ~ 2026-01-31 00:00,전주 팔복 금속가공 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 ...
12,소진공 공고조회,순창 장류 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-02-01 ~ 2026-01-31,2025-04-09 00:00 ~ 2026-01-31 00:00,순창 장류 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소공인의 ...
13,소진공 공고조회,김해 진례 도자 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-02-01 ~ 2026-01-31,2025-04-09 00:00 ~ 2026-01-31 00:00,김해 진례 도자 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소공...
14,소진공 공고조회,광주 충장 귀금속 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,광주 충장 귀금속 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소...
15,소진공 공고조회,광주 서남 인쇄 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,광주 서남 인쇄 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소공...
16,소진공 공고조회,부산 서동 의류제조 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,부산 서동 의류제조 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 ...
17,소진공 공고조회,부산범천 가죽가방신발 소공인특화지원센터 소공인 모집 공,,,,,
18,소진공 공고조회,부산 범일 의류제조 소공인특화지원센터 소공인 모집 공고,,,,,
19,소진공 공고조회,부산 범천 귀금속 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,부산 범천 귀금속 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소...
20,소진공 공고조회,대구 노원 안경제조 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,대구 노원 안경제조 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 ...
21,소진공 공고조회,대구 대봉 의류봉제 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,대구 대봉 의류봉제 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 ...
22,소진공 공고조회,대구 성내 주얼리 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,대구 성내 주얼리 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소...
23,소진공 공고조회,인천 송림 기타기계장비 소공인특화지원센터 소공인 모집,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,인천 송림 기타기계장비 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화...
24,소진공 공고조회,시흥 정왕 전기장비 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,시흥 정왕 전기장비 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 ...
25,소진공 공고조회,동탄 전자부품 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,동탄 전자부품 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소공인...
26,소진공 공고조회,안양 전자부품 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,안양 전자부품 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소공인...
27,소진공 공고조회,고양 장항 인쇄 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,고양 장항 인쇄 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소공...
28,소진공 공고조회,군포 당정 금속가공 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,군포 당정 금속가공 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 ...
29,소진공 공고조회,성남 상대원 식품제조 소공인특화지원센터 소공인 모집 공,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,성남 상대원 식품제조 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와...
30,소진공 공고조회,시흥 대야 기타기계장비 소공인특화지원센터 소공인 모집,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,시흥 대야 기타기계장비 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화...
31,소진공 공고조회,부천 신흥 전기장비 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,부천 신흥 전기장비 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 ...
32,소진공 공고조회,화성 향남 기타기계장비 소공인특화지원센터 소공인 모집,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,화성 향남 기타기계장비 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화...
33,소진공 공고조회,용인영덕 전자부품 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,용인 영덕 전자부품 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 ...
34,소진공 공고조회,서울 광진 의류제조 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,서울 광진 의류제조 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 ...
35,소진공 공고조회,서울 봉익 주얼리 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,서울 봉익 주얼리 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소...
36,소진공 공고조회,서울 장위 의류봉제 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,서울 장위 의류봉제 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 ...
37,소진공 공고조회,공주 섬유제조 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,공주섬유제조 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소공인의...
38,소진공 공고조회,청주 중앙 인쇄 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,청주중앙인쇄 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소공인의...
39,소진공 공고조회,대전 덕암 금속가공 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-08 ~ 2026-01-31,2025-04-08 00:00 ~ 2026-01-31 23:59,대전덕암금속가공 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소공...
40,소진공 공고조회,충남 금산 인삼 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-04 ~ 2026-01-31,2025-04-04 00:00 ~ 2026-01-31 00:00,충남금산인삼 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소공인의...
41,소진공 공고조회,대전 오정 기타기계장비제조 소공인특화지원센터 소공인 모,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-04 ~ 2026-01-31,2025-04-04 00:00 ~ 2026-01-31 00:00,대전오정기타기계장비제조 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화...
42,소진공 공고조회,대전 정동 인쇄 소공인특화지원센터 소공인 모집 공고,소상공인/예비창업자,지역소공인 육성-소공인 특화지원센터 설치∙운영,2025-04-04 ~ 2026-01-31,2025-04-04 00:00 ~ 2026-01-31 00:00,대전정동인쇄 소공인특화지원센터 소공인 모집 공고 소공인의 집적지 활성화와 소공인의...

In [86]:
import os

# 저장할 파일명 지정
save_filename1 = "parsed_sojingong_final.csv"
save_filename2 = "parsed_yugwan.csv"

df_sojingong_final.to_csv(save_filename1, index=False, encoding="utf-8-sig")
df_yugwan_final.to_csv(save_filename2, index=False, encoding="utf-8-sig")